/* LIFT — plan data. Hypertrophy primary, Zone 2 secondary, knee-safe, ≤45 min. */
window.LIFT_DATA = {
  profile: {
    name: "Pedro",
    weightKg: 61,
    heightCm: 163,
    bfPct: 12,
    age: 28,
    vo2: 48.5,
    vo2Target: 52,
    hrMax: 192,
    z2: [125, 134],
    level: "Avançado",
  },

  /* Mon–Fri only. Weekend is rest (optional easy walk, not programmed). */
  weekdays: [
    { dow: 1, key: "upper-a", short: "SEG", label: "Upper A" },
    { dow: 2, key: "lower-a", short: "TER", label: "Lower A" },
    { dow: 3, key: "z2", short: "QUA", label: "Zona 2" },
    { dow: 4, key: "upper-b", short: "QUI", label: "Upper B" },
    { dow: 5, key: "lower-b", short: "SEX", label: "Lower B" },
  ],

  sessions: {
    "upper-a": {
      key: "upper-a",
      title: "Upper A",
      tag: "horizontal",
      tagLabel: "Peito · Costas · Empurrar",
      kind: "lift",
      minutes: 45,
      warmup:
        "4 min. Band pull-aparts 2×12 · face pull leve 1×15 · 1 série leve no supino (50–60%). Sem tour pela academia.",
      notes: [
        "Teto 45 min. Compostos 3 séries, 2–3 min de descanso. Isoladores curtos. Se atrasar, pule o tríceps — não corte o rest dos compostos.",
        "Compostos a RPE 7–8 (1–3 reps na reserva). Isoladores a RPE 8–9.",
      ],
      exercises: [
        {
          num: "A1",
          name: "Supino reto com halteres",
          sub: "Composto · peitoral",
          sets: 3,
          reps: "6–10",
          rest: "2–3 min",
          rpe: "7–8",
          note: "Escápulas retraídas, desça até alongar o peitoral, cotovelos ~75°. Sub: chest press na máquina.",
        },
        {
          num: "B1",
          name: "Remada curvada com barra",
          sub: "Composto · dorsal",
          sets: 3,
          reps: "6–10",
          rest: "2–3 min",
          rpe: "7–8",
          note: "Tronco ~45°, cotovelos puxam para o quadril, 1s no pico. Sub: remada peito apoiado.",
        },
        {
          num: "C1",
          name: "Supino inclinado com halteres",
          sub: "Peitoral superior",
          sets: 3,
          reps: "8–12",
          rest: "2 min",
          rpe: "8",
          note: "Banco 30–45°. Alongamento no fundo. Sub: inclinado na máquina.",
        },
        {
          num: "D1",
          name: "Pulley pegada neutra",
          sub: "Dorsal · puxada vertical",
          sets: 3,
          reps: "8–12",
          rest: "90s–2 min",
          rpe: "8",
          note: "Puxe pelo cotovelo, toque o peito. Sub: pulley supinado.",
        },
        {
          num: "E1",
          name: "Elevação lateral com halteres",
          sub: "Deltóide medial",
          sets: 3,
          reps: "12–20",
          rest: "60s",
          rpe: "8",
          note: "Cotovelo levemente fletido, sobe até a orelha. Sem balanço. Sub: lateral no cabo.",
        },
        {
          num: "F1",
          name: "Tríceps pulley (corda)",
          sub: "Isolador · tríceps",
          sets: 2,
          reps: "10–15",
          rest: "60s",
          rpe: "8–9",
          note: "Abra a corda no final. Primeiro a cortar se o relógio apertar. Sub: tríceps testa.",
        },
      ],
    },

    "lower-a": {
      key: "lower-a",
      title: "Lower A",
      tag: "quad",
      tagLabel: "Quad · joelho-safe",
      kind: "lift",
      minutes: 45,
      warmup:
        "4 min. Glute bridge 2×12 · clamshell 1×12/lado · 1 série leve no Hack. Sem circuito longo.",
      notes: [
        "Teto 45 min. RDL ficou na sexta — terça é quadríceps. Descanso do Hack é 3 min; não encurte.",
        "Joelho: Hack é o principal. Amplitude só até o ponto sem dor (~90°). Se inflamar, Hack vira Leg Press 45° e você corta a extensora.",
        "Fora: agachamento livre, Smith, afundo, passada, búlgaro, salto, corrida.",
      ],
      exercises: [
        {
          num: "A1",
          name: "Hack squat",
          sub: "Composto principal · quadríceps",
          sets: 4,
          reps: "8–12",
          rest: "3 min",
          rpe: "7–8",
          note: "Pés na largura dos ombros, levemente à frente. Desça só até amplitude confortável. Sub se doer: Leg Press 45° (pés médios) nas mesmas 4 séries.",
          knee: true,
        },
        {
          num: "B1",
          name: "Leg press 45° (pés médios)",
          sub: "Quadríceps · volume",
          sets: 3,
          reps: "10–15",
          rest: "2 min",
          rpe: "7–8",
          note: "Pés no meio da plataforma. Sem fundo que enrola o quadril. Sub se o joelho reclamar: pule este e fique no Hack + extensora.",
          knee: true,
        },
        {
          num: "C1",
          name: "Cadeira extensora",
          sub: "Isolador · quadríceps",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8–9",
          note: "Amplitude dolorosa = amplitude errada. Sem carga máxima no lockout se pinçar na frente do joelho.",
          knee: true,
        },
        {
          num: "D1",
          name: "Leg curl deitado",
          sub: "Isquios · manutenção",
          sets: 2,
          reps: "10–15",
          rest: "90s",
          rpe: "8–9",
          note: "Volume curto de propósito — o trabalho pesado de isquio é sexta. Quadril colado no banco. Sub: curl sentado.",
        },
        {
          num: "E1",
          name: "Panturrilha em pé",
          sub: "Gastrocnêmio",
          sets: 3,
          reps: "10–20",
          rest: "60s",
          rpe: "8",
          note: "Amplitude total, 1s no topo. Sub: panturrilha no leg press.",
        },
      ],
    },

    z2: {
      key: "z2",
      title: "Zona 2",
      tag: "cardio",
      tagLabel: "Base aeróbia · VO₂",
      kind: "cardio",
      minutes: 45,
      warmup: "Os primeiros 5 min na máquina já são o aquecimento. Cadência solta, depois entre na zona.",
      notes: [
        "Sessão inteira = 45 min no relógio, incluindo subir na bike. Sem musculação neste dia.",
        "Máquina: bicicleta (preferida) ou elíptico. Escada só se o joelho estiver quieto. Sem corrida, sem salto.",
        "Teste da fala: frases completas sim, cantar não. Se ofegar, abaixe.",
      ],
      exercises: [],
      cardio: {
        machine: "Bike ou elíptico",
        hr: "125–134 bpm",
        hrNote: "65–70% da FCmáx (192). Zona 2 de verdade — não é “cardio médio de academia”.",
      },
    },

    "upper-b": {
      key: "upper-b",
      title: "Upper B",
      tag: "vertical",
      tagLabel: "Costas · Ombro · Isoladores",
      kind: "lift",
      minutes: 45,
      warmup:
        "4 min. Face pull leve 1×15 · 1 série leve de pulley · 1 série leve de desenvolvimento.",
      notes: [
        "Teto 45 min. Sem finisher de cardio neste dia — a Zona 2 é quarta. Se atrasar, pule o tríceps.",
        "Compostos a RPE 7–8. Isoladores a RPE 8–9.",
      ],
      exercises: [
        {
          num: "A1",
          name: "Barra fixa (pronada)",
          sub: "Dorsal · composto vertical",
          sets: 3,
          reps: "5–8",
          rest: "2–3 min",
          rpe: "7–8",
          note: "Depressão escapular antes de puxar. Lastre se fechar 8 fácil. Sub: pulley barra larga.",
        },
        {
          num: "B1",
          name: "Desenvolvimento com halteres sentado",
          sub: "Deltóide · empurrar vertical",
          sets: 3,
          reps: "8–12",
          rest: "2 min",
          rpe: "8",
          note: "Não trave o cotovelo no topo. Controle 2s na descida. Sub: desenvolvimento na máquina.",
        },
        {
          num: "C1",
          name: "Crucifixo no cabo (alongado)",
          sub: "Peitoral · tensão contínua",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8–9",
          note: "Polea alta → baixa. Cotovelo levemente fletido, alongue o peito. Sub: peck deck.",
        },
        {
          num: "D1",
          name: "Face pull com corda",
          sub: "Deltóide posterior · ombro",
          sets: 2,
          reps: "15–20",
          rest: "60s",
          rpe: "7",
          note: "Não pule. Puxe para a cara, cotovelos altos. Sub: rotação externa com elástico.",
        },
        {
          num: "E1",
          name: "Elevação lateral no cabo",
          sub: "Deltóide medial",
          sets: 3,
          reps: "12–20",
          rest: "60s",
          rpe: "8",
          note: "Cabo cruzado, abaixo do quadril. Sub: lateral com haltere.",
        },
        {
          num: "F1",
          name: "Rosca inclinada com halteres",
          sub: "Bíceps · alongado",
          sets: 3,
          reps: "8–12",
          rest: "90s",
          rpe: "8–9",
          note: "Banco 45–60°, braço atrás do tronco. Sem balanço. Sub: rosca no cabo baixo.",
        },
        {
          num: "G1",
          name: "Tríceps acima da cabeça",
          sub: "Cabeça longa",
          sets: 2,
          reps: "10–15",
          rest: "75s",
          rpe: "8",
          note: "Cotovelo quieto. Primeiro a cortar se o relógio apertar. Sub: pulley acima da cabeça.",
        },
      ],
    },

    "lower-b": {
      key: "lower-b",
      title: "Lower B",
      tag: "posterior",
      tagLabel: "Glúteo · Isquios · Sem joelho fundo",
      kind: "lift",
      minutes: 45,
      warmup:
        "4 min. Hip thrust sem carga 2×12 · ponte unipodal 1×8/lado. Sem monster walk longo.",
      notes: [
        "Teto 45 min. Aqui está o RDL — terça não teve. Sem terra convencional.",
        "Sem afundo, sem pés baixos no press, sem fundo que pinça o joelho.",
      ],
      exercises: [
        {
          num: "A1",
          name: "Hip thrust com barra",
          sub: "Glúteo máximo · composto",
          sets: 4,
          reps: "8–12",
          rest: "2–3 min",
          rpe: "8",
          note: "Banco na omoplata, queixo neutro, 1s no topo. Sub: elevação pélvica no chão com barra.",
        },
        {
          num: "B1",
          name: "RDL com barra",
          sub: "Isquios / posterior · dobradiça",
          sets: 3,
          reps: "8–10",
          rest: "2–3 min",
          rpe: "7–8",
          note: "Barra desliza na perna, quadril pra trás, lombar neutra. Não é terra. Sub: RDL com halteres.",
        },
        {
          num: "C1",
          name: "Leg curl sentado",
          sub: "Isquios alongados",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8–9",
          note: "Quadril flexionado = melhor estímulo de isquio. Sub: curl deitado.",
        },
        {
          num: "D1",
          name: "Extensão lombar 45° ou pull-through",
          sub: "Cadeia posterior",
          sets: 2,
          reps: "10–15",
          rest: "90s",
          rpe: "8",
          note: "Dobradiça de quadril. Primeiro a cortar se o relógio apertar. Sub: good morning leve.",
        },
        {
          num: "E1",
          name: "Panturrilha sentado",
          sub: "Sóleo",
          sets: 3,
          reps: "12–20",
          rest: "60s",
          rpe: "8",
          note: "Joelho fletido — diferente da panturrilha em pé de terça. Amplitude total.",
        },
      ],
    },
  },

  /* 4-week mesocycle, repeats. Week-of-plan is calendar-based. */
  meso: [
    {
      week: 1,
      name: "Acúmulo",
      liftNote: "Volume base. 45 min no relógio. Feche a faixa de reps com boa forma antes de subir carga.",
      cardio: {
        title: "LISS — Zona 2",
        duration: "40 min",
        detail:
          "Bike ou elíptico. 5 min fácil + 35 min em 125–134 bpm. Sem intervalos. Porta a porta ≤45 min.",
      },
    },
    {
      week: 2,
      name: "Acúmulo +",
      liftNote: "Se fechou o topo da faixa na semana 1, suba a carga no composto. Senão, some 1–2 reps. Continua 45 min.",
      cardio: {
        title: "LISS — Zona 2",
        duration: "40 min",
        detail:
          "Mesma duração da semana 1 (teto de 45). A progressão é ficar mais tempo no meio da zona, não alongar a sessão.",
      },
    },
    {
      week: 3,
      name: "Estímulo VO₂",
      liftNote: "Mesmo volume de musculação, ainda 45 min. O extra é o bloco de VO₂ na quarta — na bike.",
      cardio: {
        title: "Z2 + intervalos na bike",
        duration: "40 min",
        detail:
          "5 min fácil → 8 min Z2 → 6× (1 min forte RPE 8 / 2 min bem fácil) → 8 min Z2. Só bike. Cabe em 45. Nunca esteira, nunca no dia de lower.",
      },
    },
    {
      week: 4,
      name: "Deload",
      liftNote: "2 séries por exercício, RPE ~6, longe da falha. Deve sobrar tempo. Não teste carga.",
      cardio: {
        title: "Z2 curto",
        duration: "20–25 min",
        detail: "Só fácil. Sem intervalos. Sessão bem abaixo de 45.",
      },
    },
  ],

  banned: [
    "Agachamento livre",
    "Agachamento no Smith",
    "Afundo / passada / búlgaro",
    "Corrida e sprint na esteira",
    "Pulo, box jump, corda",
    "Extensora pesada em lockout se pinçar o joelho",
    "Terra convencional toda semana (fadiga > hipertrofia neste bloco)",
  ],

  why: [
    {
      t: "Por que 4 musculações + 1 cardio, em 45 min",
      d: "O descanso de 2–3 min nos compostos ficou. O que saiu foi série extra e exercício extra. Terça é quad, sexta é posterior — o RDL não compete com o Hack no mesmo relógio. Semanalmente ainda dá ~9–10 séries duras nos músculos principais.",
    },
    {
      t: "O que a ciência está dizendo (2024–2026)",
      d: "Tensão mecânica progressiva é o motor. ACSM 2026: ~10 séries duras por músculo é um começo sólido. Hipertrofia acontece de ~5 a 20 reps se a série for difícil (0–3 RIR). Descanso >60s rende mais porque você mantém a carga — por isso o corte foi de volume, não de rest.",
    },
    {
      t: "Zona 2 e VO₂",
      d: "A dose de cardio do plano é a quarta (40 min, teto 45). Quinta não tem mais finisher — não cabia. Semana 3 de cada bloco: intervalos curtos na bike. Sem corrida.",
    },
    {
      t: "Joelho",
      d: "Hack e press em amplitude sem dor. Sem flexão profunda sob fadiga, sem impacto. Se um dia inflamar: Hack → Leg Press, corte a extensora, e a quarta continua sendo só bike.",
    },
  ],
};
