/* LIFT — plan data. Hypertrophy primary, Zone 2 secondary, knee-safe. */
window.LIFT_DATA = {
  profile: {
    name: "Pedro",
    weightKg: 61,
    heightCm: 163,
    bfPct: 12,
    age: 28,
    vo2: 48.5,
    vo2Target: 52,
    hrMax: 192,
    z2: [125, 134],
    level: "Avançado",
  },

  /* Mon–Fri only. Weekend is rest (optional easy walk, not programmed). */
  weekdays: [
    { dow: 1, key: "upper-a", short: "SEG", label: "Upper A" },
    { dow: 2, key: "lower-a", short: "TER", label: "Lower A" },
    { dow: 3, key: "z2", short: "QUA", label: "Zona 2" },
    { dow: 4, key: "upper-b", short: "QUI", label: "Upper B" },
    { dow: 5, key: "lower-b", short: "SEX", label: "Lower B" },
  ],

  sessions: {
    "upper-a": {
      key: "upper-a",
      title: "Upper A",
      tag: "horizontal",
      tagLabel: "Peito · Costas · Empurrar",
      kind: "lift",
      warmup:
        "5–8 min. Band pull-aparts 2×15 · rotação escapular com haltere leve 2×10 · face pull leve 2×15 · 1 série leve no supino (50–60%).",
      notes: [
        "Compostos a RPE 7–8 (1–3 reps na reserva). Isoladores a RPE 8–9.",
        "Descanso: 2–3 min nos compostos, 60–90s nos isoladores.",
      ],
      exercises: [
        {
          num: "A1",
          name: "Supino reto com halteres",
          sub: "Composto · peitoral",
          sets: 4,
          reps: "6–10",
          rest: "2–3 min",
          rpe: "7–8",
          note: "Escápulas retraídas, desça até alongar o peitoral, cotovelos ~75° do tronco. Halteres são mais seguros sozinho do que barra. Sub: chest press na máquina.",
        },
        {
          num: "B1",
          name: "Remada curvada com barra",
          sub: "Composto · dorsal / espessura",
          sets: 4,
          reps: "6–10",
          rest: "2–3 min",
          rpe: "7–8",
          note: "Tronco ~45°, cotovelos puxam para o quadril, 1s no pico. Não arredonde a lombar. Sub: remada peito apoiado (ainda melhor se a lombar estiver cansada).",
        },
        {
          num: "C1",
          name: "Supino inclinado com halteres",
          sub: "Peitoral superior",
          sets: 3,
          reps: "8–12",
          rest: "2 min",
          rpe: "8",
          note: "Banco 30–45°. Mesmo padrão do reto: alongamento no fundo, sem bater os halteres no topo. Sub: inclinado na máquina.",
        },
        {
          num: "D1",
          name: "Pulley pegada neutra",
          sub: "Dorsal · puxada vertical",
          sets: 3,
          reps: "8–12",
          rest: "90s",
          rpe: "8",
          note: "Puxe pelo cotovelo, toque o peito na barra/triângulo. Complementa a remada (horizontal + vertical). Sub: pulley supinado.",
        },
        {
          num: "E1",
          name: "Elevação lateral com halteres",
          sub: "Deltóide medial",
          sets: 4,
          reps: "12–20",
          rest: "60s",
          rpe: "8",
          note: "Cotovelo levemente fletido, sobe até a linha da orelha. Carga leve e limpa > balanço. Sub: lateral no cabo.",
        },
        {
          num: "F1",
          name: "Rosca martelo",
          sub: "Bíceps + braquiorradial",
          sets: 3,
          reps: "10–14",
          rest: "60–90s",
          rpe: "8–9",
          note: "Pegada neutra, excêntrico de 2s. Sub: rosca no cabo com corda.",
        },
        {
          num: "G1",
          name: "Tríceps pulley (corda)",
          sub: "Cabeça lateral",
          sets: 3,
          reps: "10–15",
          rest: "60s",
          rpe: "8–9",
          note: "Abra a corda no final. Não jogue o tronco pra frente. Sub: tríceps testa.",
        },
      ],
    },

    "lower-a": {
      key: "lower-a",
      title: "Lower A",
      tag: "quad",
      tagLabel: "Quad · joelho-safe",
      kind: "lift",
      warmup:
        "5–8 min. Glute bridge 2×15 · clamshell com band 2×15/lado · swing de perna frente/lado 10 · 1–2 séries leves no Hack.",
      notes: [
        "Joelho: Hack é o principal. Amplitude só até o ponto sem dor (muitas vezes ~90°). Se inflamar, troque o Hack por Leg Press 45° no mesmo dia.",
        "Fora: agachamento livre, Smith, afundo, passada, agachamento búlgaro, salto, corrida.",
      ],
      exercises: [
        {
          num: "A1",
          name: "Hack squat",
          sub: "Composto principal · quadríceps",
          sets: 4,
          reps: "8–12",
          rest: "3 min",
          rpe: "7–8",
          note: "Pés na largura dos ombros, levemente à frente. Desça só até amplitude confortável. Não force o fundo se o joelho falar. Sub obrigatória se doer: Leg Press 45° (pés médios).",
          knee: true,
        },
        {
          num: "B1",
          name: "RDL com barra",
          sub: "Isquios / posterior · dobradiça",
          sets: 3,
          reps: "8–10",
          rest: "3 min",
          rpe: "7–8",
          note: "Barra desliza na perna, quadril vai pra trás, lombar neutra. Sinta o alongamento nos isquios. Não é terra convencional. Sub: RDL com halteres.",
        },
        {
          num: "C1",
          name: "Leg press 45° (pés médios)",
          sub: "Quadríceps · volume estável",
          sets: 3,
          reps: "10–15",
          rest: "2 min",
          rpe: "7–8",
          note: "Pés no meio da plataforma. Não desça até o quadril enrolar. Pare antes da dor. Sub se o joelho reclamar: só Hack (pule este) ou encurte a amplitude.",
          knee: true,
        },
        {
          num: "D1",
          name: "Cadeira extensora",
          sub: "Isolador · quadríceps alongado",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8–9",
          note: "Amplitude dolorosa = amplitude errada. Evite carga máxima no lockout completo se pinçar na frente do joelho. Trabalhe o meio da curva e o alongamento que for confortável.",
          knee: true,
        },
        {
          num: "E1",
          name: "Leg curl deitado",
          sub: "Isolador · isquios",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8–9",
          note: "Quadril colado no banco. Excêntrico 2–3s. Sub: leg curl sentado.",
        },
        {
          num: "F1",
          name: "Panturrilha em pé",
          sub: "Gastrocnêmio",
          sets: 4,
          reps: "10–20",
          rest: "60s",
          rpe: "8",
          note: "Amplitude total, 1s no topo. Sub: panturrilha no leg press.",
        },
      ],
    },

    z2: {
      key: "z2",
      title: "Zona 2",
      tag: "cardio",
      tagLabel: "Base aeróbia · VO₂",
      kind: "cardio",
      warmup: "5 min fácil na mesma máquina, cadência solta, antes de entrar na zona.",
      notes: [
        "Máquina: bicicleta ergométrica (preferida) ou elíptico. Simulador de escada só se o joelho estiver quieto. Sem corrida, sem salto, sem HIIT em esteira.",
        "Teste da fala: frases completas sim, cantar não. Se ofegar, abaixe.",
      ],
      exercises: [],
      cardio: {
        machine: "Bike ou elíptico",
        hr: "125–134 bpm",
        hrNote: "65–70% da FCmáx (192). Zona 2 de verdade — não é “cardio médio de academia”.",
      },
    },

    "upper-b": {
      key: "upper-b",
      title: "Upper B",
      tag: "vertical",
      tagLabel: "Costas · Ombro · Isoladores",
      kind: "lift",
      warmup:
        "5 min. Face pull leve 2×15 · dislocação com elástico 1×10 · 1 série leve de pulley e 1 de desenvolvimento.",
      notes: [
        "Depois da musculação: Zona 2 fácil 20–25 min na bike (finisher). Não precisa ser um segundo treino em casa.",
        "Se o dia estiver pesado, faça o finisher mais curto (15 min) — não pule o levantamento.",
      ],
      exercises: [
        {
          num: "A1",
          name: "Barra fixa (pronada)",
          sub: "Dorsal · composto vertical",
          sets: 4,
          reps: "5–8",
          rest: "3 min",
          rpe: "7–8",
          note: "Depressão escapular antes de puxar, queixo passa a barra. Lastre se fechar 8 fácil. Sub: pulley barra larga na mesma intenção de carga.",
        },
        {
          num: "B1",
          name: "Desenvolvimento com halteres sentado",
          sub: "Deltóide · empurrar vertical",
          sets: 3,
          reps: "8–12",
          rest: "2 min",
          rpe: "8",
          note: "Não trave o cotovelo no topo. Controle 2s na descida. Sub: desenvolvimento na máquina (bom se o ombro preferir).",
        },
        {
          num: "C1",
          name: "Crucifixo no cabo (alongado)",
          sub: "Peitoral · tensão contínua",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8–9",
          note: "Polea alta → baixa, ou crossover clássico. Cotovelo levemente fletido, alongue o peito no começo da repetição. Sub: peck deck.",
        },
        {
          num: "D1",
          name: "Pulldown braços estendidos",
          sub: "Dorsal · alongamento",
          sets: 3,
          reps: "12–15",
          rest: "90s",
          rpe: "8",
          note: "Polea alta, cotovelo quase estendido, arco até o quadril. Também chamado de straight-arm pulldown. Sub: pullover com haltere.",
        },
        {
          num: "E1",
          name: "Face pull com corda",
          sub: "Deltóide posterior · ombro",
          sets: 3,
          reps: "15–20",
          rest: "60s",
          rpe: "7",
          note: "Não pule. Puxe para a cara, cotovelos altos, abra a corda. Saúde de ombro. Sub: rotação externa com elástico.",
        },
        {
          num: "F1",
          name: "Elevação lateral no cabo",
          sub: "Deltóide medial · alongado",
          sets: 4,
          reps: "12–20",
          rest: "60s",
          rpe: "8",
          note: "Cabo cruzado, abaixo do quadril. Tensão no alongamento. Sub: lateral com haltere.",
        },
        {
          num: "G1",
          name: "Rosca inclinada com halteres",
          sub: "Bíceps · cabeça longa alongada",
          sets: 3,
          reps: "8–12",
          rest: "90s",
          rpe: "8–9",
          note: "Banco 45–60°, braço pendurado atrás do tronco. Não balançar. Sub: rosca no cabo baixo (bayesian).",
        },
        {
          num: "H1",
          name: "Tríceps acima da cabeça",
          sub: "Cabeça longa · alongamento",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8",
          note: "Haltere ou cabo. Cotovelo quieto, só o antebraço mexe. Sub: pulley com corda acima da cabeça.",
        },
        {
          num: "Z2",
          name: "Finisher Zona 2",
          sub: "Bike · 20–25 min fácil",
          sets: 1,
          reps: "20–25 min",
          rest: "—",
          rpe: "Z2",
          cardioItem: true,
          note: "Mesma sessão, na bike. 125–134 bpm. Semana de deload: 15 min ou pule. Não é treino de perna — se o joelho estiver sensível, elíptico.",
        },
      ],
    },

    "lower-b": {
      key: "lower-b",
      title: "Lower B",
      tag: "posterior",
      tagLabel: "Glúteo · Isquios · Sem joelho fundo",
      kind: "lift",
      warmup:
        "5–8 min. Hip thrust sem carga 2×15 · monster walk 2×10 m · ponte unipodal 2×10/lado.",
      notes: [
        "Sem terra convencional nesta ficha. RDL + hip thrust crescem mais o posterior com menos fadiga sistêmica — melhor para hipertrofia no seu volume.",
        "Pés altos no leg press: mais glúteo/isquio, menos cisalhamento no joelho do que pés baixos.",
      ],
      exercises: [
        {
          num: "A1",
          name: "Hip thrust com barra",
          sub: "Glúteo máximo · composto",
          sets: 4,
          reps: "8–12",
          rest: "2–3 min",
          rpe: "8",
          note: "Banco na omoplata, queixo neutro, retroversão no topo, 1s de contração. Sub: elevação pélvica no chão com barra.",
        },
        {
          num: "B1",
          name: "Leg press 45° (pés altos)",
          sub: "Glúteo / posterior",
          sets: 3,
          reps: "10–15",
          rest: "2 min",
          rpe: "7–8",
          note: "Pés na parte de cima da plataforma. Amplitude controlada, sem fundo que pinça o joelho. Não é afundo. Sub: mais uma série de hip thrust.",
          knee: true,
        },
        {
          num: "C1",
          name: "Leg curl sentado",
          sub: "Isquios alongados",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8–9",
          note: "Quadril flexionado = melhor estímulo de isquio do que o curl deitado. Sub: curl deitado.",
        },
        {
          num: "D1",
          name: "Extensão lombar 45° ou puxada no cabo (pull-through)",
          sub: "Posterior da cadeia",
          sets: 3,
          reps: "10–15",
          rest: "90s",
          rpe: "8",
          note: "Dobradiça de quadril, não é “abdominada invertida”. Sinta glúteo e isquio. Sub: good morning leve.",
        },
        {
          num: "E1",
          name: "Panturrilha sentado",
          sub: "Sóleo",
          sets: 4,
          reps: "12–20",
          rest: "60s",
          rpe: "8",
          note: "Joelho fletido isola o sóleo — diferente da panturrilha em pé de terça. Amplitude total.",
        },
      ],
    },
  },

  /* 4-week mesocycle, repeats. Week-of-plan is calendar-based. */
  meso: [
    {
      week: 1,
      name: "Acúmulo",
      liftNote: "Volume base. Feche a faixa de reps com boa forma antes de subir carga.",
      cardio: {
        title: "LISS — Zona 2",
        duration: "40 min",
        detail:
          "Bike ou elíptico. 125–134 bpm o tempo todo depois do aquecimento. Sem intervalos.",
      },
    },
    {
      week: 2,
      name: "Acúmulo +",
      liftNote: "Se fechou o topo da faixa na semana 1, suba a carga no composto. Senão, some 1–2 reps.",
      cardio: {
        title: "LISS — Zona 2",
        duration: "45–50 min",
        detail: "Mesma zona. +5–10 min em relação à semana 1. Ainda sem sprint.",
      },
    },
    {
      week: 3,
      name: "Estímulo VO₂",
      liftNote: "Mesmo volume de musculação. O extra desta semana é o bloco de VO₂ na quarta — na bike.",
      cardio: {
        title: "Z2 + intervalos na bike",
        duration: "~40 min",
        detail:
          "10 min Z2 → 6× (1 min forte RPE 8 / 2 min bem fácil) → 10 min Z2. Só bike. Nunca esteira, nunca no dia de lower.",
      },
    },
    {
      week: 4,
      name: "Deload",
      liftNote: "2 séries por exercício, RPE ~6, longe da falha. Não teste carga. Crescer acontece aqui.",
      cardio: {
        title: "Z2 curto",
        duration: "20–25 min",
        detail: "Só fácil. Sem intervalos. Finisher de quinta: 15 min ou descanse.",
      },
    },
  ],

  banned: [
    "Agachamento livre",
    "Agachamento no Smith",
    "Afundo / passada / búlgaro",
    "Corrida e sprint na esteira",
    "Pulo, box jump, corda",
    "Extensora pesada em lockout se pinçar o joelho",
    "Terra convencional toda semana (fadiga > hipertrofia neste bloco)",
  ],

  why: [
    {
      t: "Por que 4 musculações + 1 cardio",
      d: "Você já é avançado e leve (61 kg / ~12%). Hipertrofia pede ~10–16 séries duras por músculo, 2× na semana — isso cabe em Upper/Lower/Upper/Lower. O 5º dia de academia do plano antigo já era opcional. Quarta livre de carga descansa o joelho entre os dois lowers e deixa a Zona 2 ter qualidade de verdade.",
    },
    {
      t: "O que a ciência está dizendo (2024–2026)",
      d: "Tensão mecânica progressiva é o motor. ACSM 2026: comece perto de 10 séries duras por músculo e ajuste. Hipertrofia acontece de ~5 a 20 reps se a série for difícil (0–3 RIR). Descanso >60s rende um pouco mais porque você mantém a carga. Alongar o músculo no exercício (RDL, curl sentado, voador, tríceps acima da cabeça) ajuda; não precisa de “partials” forçados.",
    },
    {
      t: "Zona 2 e VO₂",
      d: "Z2 sozinha constrói base (volume sistólico, mitocôndria). VO₂ máximo sobe de verdade com um pouco de intensidade — por isso a semana 3 de cada bloco tem intervalos curtos na bike. 80/20: a maior parte fácil, um pedaço difícil. Sem corrida.",
    },
    {
      t: "Joelho",
      d: "Hack e press em amplitude sem dor. Sem flexão profunda sob fadiga, sem impacto. Se um dia inflamar: Hack → Leg Press, corte a extensora, e a quarta continua sendo só bike.",
    },
  ],
};
